# Generated by Django 4.1.3 on 2023-01-03 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='sexo',
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(default=datetime.datetime(2023, 1, 3, 23, 31, 10, 688669, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
