# Generated by Django 4.1.3 on 2023-01-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0002_remove_persona_sexo_persona_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('subtutilo', models.CharField(max_length=60)),
                ('Parrafo', models.CharField(max_length=60)),
                ('autor', models.CharField(max_length=60)),
            ],
        ),
    ]
