# Generated by Django 4.1.3 on 2023-01-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0004_alter_blogs_parrafo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='subtutilo',
            new_name='subtitulo',
        ),
    ]
