# Generated by Django 4.1.3 on 2023-01-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0005_rename_subtutilo_blogs_subtitulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='Parrafo',
            new_name='parrafo',
        ),
    ]
