# Generated by Django 4.1.3 on 2023-01-04 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0006_rename_parrafo_blogs_parrafo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='fecha_creado',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 4, 20, 59, 23, 136950, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
