# Generated by Django 4.1.3 on 2023-01-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0007_blogs_fecha_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='fecha_creado',
            field=models.DateField(blank=True),
        ),
    ]
