# Generated by Django 4.1.3 on 2023-01-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0008_alter_blogs_fecha_creado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='fecha_creado',
        ),
    ]
