# Generated by Django 4.1.3 on 2023-01-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0010_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='imagen',
            field=models.ImageField(default=1, upload_to='blogs'),
            preserve_default=False,
        ),
    ]
