# Generated by Django 4.1.3 on 2023-01-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0011_blogs_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
