# Generated by Django 4.1.3 on 2023-01-12 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0015_blogs_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='imagen',
        ),
    ]
