# Generated by Django 4.1.3 on 2023-01-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0016_remove_blogs_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='imagen',
            field=models.ImageField(default=1, upload_to='blogs'),
            preserve_default=False,
        ),
    ]
