# Generated by Django 4.1.3 on 2023-01-14 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0017_blogs_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='imagen',
            new_name='blogsimagen',
        ),
    ]
