# Generated by Django 4.1.3 on 2023-01-14 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppFinal', '0018_rename_imagen_blogs_blogsimagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blogsimagen',
        ),
        migrations.CreateModel(
            name='BlogsImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Blogs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
