# Generated by Django 4.1.3 on 2023-01-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0019_remove_blogs_blogsimagen_blogsimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='imagen',
            field=models.ImageField(default=1, upload_to='blogs'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BlogsImagen',
        ),
    ]
