# Generated by Django 4.1.3 on 2023-01-14 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0021_remove_blogs_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='blogs')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFinal.blogs')),
            ],
        ),
    ]
