# Generated by Django 4.1.3 on 2023-01-15 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0024_remove_blogs_imagen_imegenblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imegenblog',
            name='user',
        ),
        migrations.AddField(
            model_name='imegenblog',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppFinal.blogs'),
            preserve_default=False,
        ),
    ]
