# Generated by Django 4.1.3 on 2023-01-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0025_remove_imegenblog_user_imegenblog_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imegenblog',
            name='imagen',
            field=models.ImageField(upload_to='blogs'),
        ),
    ]
