# Generated by Django 4.1.3 on 2023-01-15 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0026_alter_imegenblog_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImegenBlog',
            new_name='ImagenBlog',
        ),
    ]
