# Generated by Django 4.1.3 on 2023-01-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0027_rename_imegenblog_imagenblog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenblog',
            old_name='blog',
            new_name='titulo',
        ),
    ]
