# Generated by Django 4.1.3 on 2023-01-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0028_rename_blog_imagenblog_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='imagen',
            field=models.ImageField(default=1, upload_to='blogs'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ImagenBlog',
        ),
    ]
