# Generated by Django 4.1.3 on 2023-01-18 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0031_remove_blogs_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='creado',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 1, 18, 1, 40, 1, 89323, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
