# Generated by Django 4.1.3 on 2023-01-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0032_blogs_creado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
