# Generated by Django 4.1.3 on 2023-01-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0034_blogs_parrafoamplio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='parrafoamplio',
            field=models.CharField(max_length=900),
        ),
    ]
