# Generated by Django 4.1.3 on 2023-01-19 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0036_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
