# Generated by Django 4.1.3 on 2023-01-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRegistro', '0002_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
